# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4db55291599ce0b9652ad6a43180ab0cecbb725c0e5e2f9aa689ac7523beff6df74a35f68b5ec9fc8408bf6febe9a54b6ea25d12f093ac37cd855dca7f93800

test:
  secret_key_base: 36aca8d5577e2da8130a79bbc8bce2480c07c79714a81401a86c0efe91f0e9381df819563bba6861f7dd2604dbb37ae58c0730e62cb1bf77e40fe994f462874d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
